export const shopConfig = {
  name: "Rowan Coffee",
  tagline: "Striving for balance",
  logoPath: "/rowan-logo.png",
  location: "Asheville, NC",
  phone: "(828) 555-0123",
  rewardDescription: "free drink",
  finePrint: "Not valid on smoothies or frappes. One stamp per drink",
  stampsRequired: 9,
  colors: {
    background: "#DFDFD8",
    foreground: "#1a1210",
    headerBg: "#000000",
    headerText: "#E8D9B0",
    headerTextMuted: "rgba(232,217,176,0.55)",
    brandPrimary: "#7B5A2A",
    brandLight: "#8F6B41",
    brandDark: "#000000",
    cream: "#F5EFE6",
    stampEmpty: "#E8DDD4",
    stampFilled: "#7B5A2A",
    rewardBg: "#FFF9F0",
  },
} as const;
